name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clean Project
      run: mvn clean

    - name: Package WAR
      run: mvn package

    - name: Deploy to Tomcat
      env:
        TOMCAT_URL: http://13.233.92.230:8081/
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}
      run: |
        WAR_FILE=$(find target -name "*.war" | head -n 1)
        echo "Deploying $WAR_FILE to $TOMCAT_URL"
        curl -u "$TOMCAT_USER:$TOMCAT_PASS" --upload-file "$WAR_FILE" "$TOMCAT_URL/manager/text/deploy?path=/test&update=true"
