name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Find WAR file
        id: find_war
        run: echo "WAR=$(find webapp/target -name '*.war' | head -n 1)" >> $GITHUB_ENV

      - name: Upload WAR to Tomcat via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USER }}
          password: ${{ secrets.TOMCAT_PASS }}
          source: ${{ env.WAR }}
          target: /path/to/tomcat/webapps/

      # Optional: Deploy via Tomcat Manager (HTTP API)
      # - name: Deploy WAR via Tomcat Manager
      #   run: |
      #     curl --upload-file ${{ env.WAR }} "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }}@${{ secrets.TOMCAT_HOST }}:8081/manager/text/deploy?path=/yourcontext&update=true"
